id = "wren-lsp"
name = "Wren"
description = "Wren language support with wren-lsp integration."
version = "0.0.1"
schema_version = 1
authors = ["Jossephus <jossephus@users.noreply.github.com>"]
repository = "https://github.com/jossephus/wren-lsp"

[language_servers.wren-lsp]
name = "wren-lsp"
languages = ["Wren"]

[grammars.wren]
repository = "https://github.com/jossephus/tree-sitter-wren"
rev = "629c4f69c584bbbc113a9c13e6fd7b565c168f34"
