name = "Wren"
grammar = "wren"
path_suffixes = ["wren"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
tab_size = 2

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
